### ISSUE TITLE
Ruff Crashes with ValueError

### ISSUE THREAD

**Issue by rajeee** [astral-sh/ruff-vscode#132]
Ruff shows this output in VS Code. 

```
Using bundled executable: c:\Users\rajen\.vscode\extensions\charliermarsh.ruff-2023.6.0-win32-x64\bundled\libs\bin\ruff.exe
Running Ruff with: ['c:\\Users\\rajen\\.vscode\\extensions\\charliermarsh.ruff-2023.6.0-win32-x64\\bundled\\libs\\bin\\ruff.exe', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', 'line-length=120', '--stdin-filename', 'c:\\Users\\rajen\\PycharmProjects\\Python Playground\\empty.py']
Failed to handle user defined notification "textDocument/didOpen": (DidOpenTextDocumentParams(text_document=TextDocumentItem(uri='file:///c%3A/Users/rajen/PycharmProjects/Python%20Playground/empty.py', language_id='python', version=1, text='')),)
Traceback (most recent call last):
  File "c:\Users\rajen\.vscode\extensions\charliermarsh.ruff-2023.6.0-win32-x64\bundled\libs\pygls\protocol.py", line 84, in decorator
    self._execute_notification(user_func, *args, **kwargs)
  File "c:\Users\rajen\.vscode\extensions\charliermarsh.ruff-2023.6.0-win32-x64\bundled\libs\pygls\protocol.py", line 228, in _execute_notification
    handler(*params)
  File "c:\Users\rajen\.vscode\extensions\charliermarsh.ruff-2023.6.0-win32-x64\bundled\libs\ruff_lsp\server.py", line 85, in did_open
    diagnostics: list[Diagnostic] = _linting_helper(document)
  File "c:\Users\rajen\.vscode\extensions\charliermarsh.ruff-2023.6.0-win32-x64\bundled\libs\ruff_lsp\server.py", line 117, in _linting_helper
    return _parse_output_using_regex(result.stdout) if result.stdout else []
  File "c:\Users\rajen\.vscode\extensions\charliermarsh.ruff-2023.6.0-win32-x64\bundled\libs\ruff_lsp\server.py", line 155, in _parse_output_using_regex
    start = Position(
  File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
    __attr_validator_character(self, __attr_character, self.character)
  File "c:\Users\rajen\.vscode\extensions\charliermarsh.ruff-2023.6.0-win32-x64\bundled\libs\lsprotocol\validators.py", line 45, in uinteger_validator
    raise ValueError(
ValueError: Position.character should be in range [0:2147483647], but was -1.
```

**Comment by charliermarsh** [comment]
Thanks for the trace!

**Comment by charliermarsh** [comment]
This is probably a bug in Ruff. Will look into it.

**Comment by charliermarsh** [comment]
Are you able to share the file contents?

**Comment by rajeee** [comment]
It seems to be an issue with VS Code integration. I updated the traceback to include all of the info. The file empty.py is literally empty.

**Comment by lasinludwig** [comment]
I think I have pretty much the same problem. When I have Ruff activated and try to save any file, all the code in that file gets deleted and I get this error:

`Unexpected error in LSP server, see server's logs for details`

I also described it in issue #58 , but that issue derailed a bit and was closed.

**Comment by charliermarsh** [comment]
I fixed one thing in Ruff that _could_ be the cause of this. It would've gone out in 0.0.248.

**Comment by lasinludwig** [comment]
I just tried out the pre-release version and the LSP server doesn't crash anymore. 👍

However now I'm getting the following errors on every file:
- The system cannot find the file specified. (os error 2) Ruff(E902) [Ln 1, Col 1]
- The filename, directory name, or volume label syntax is incorrect. (os error 123) Ruff(E902) [Ln 1, Col 1]

Also I still have the problem that when I try to save a file, all the code in it gets deleted.

...is this a separate issue?

**Comment by charliermarsh** [comment]
Yeah I figured this was what was happening -- that there was some kind of IO error, and Ruff was returning a bad value for _that_ error, which was causing the server to crash. Now, at least, we can see the error without the LSP crashing.

**Comment by lasinludwig** [comment]
Just tried it again after a while and it doesn't crash anymore! 😃

There's still the problem, that it deletes the entire contents of the file when I save, but I was able to get around that by disabling the "organize imports" option. 👍

**Comment by tuhinsharma121** [comment]
I am encountering the same error for ruff==0.3.7 python --version is 3.11

>ruff fix   
                      
```warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.  
fix:1:1: E902 No such file or directory (os error 2)  
Found 1 error.
```

Is there any fix?

**Comment by trag1c** [comment]
> I am encountering the same error for ruff==0.3.7 python --version is 3.11
> 
> > ruff fix
> 
> ```
> warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.  
> fix:1:1: E902 No such file or directory (os error 2)  
> Found 1 error.
> ```
> 
> Is there any fix?

What you likely want is `ruff check <path> --fix`; as you can see in the output `ruff fix` gets interpreted as "check the file called `fix`"

**Comment by arseru** [comment]
I hit a very similar issue today - trying to save a file (from inside a devcontainer with ruff-vscode v2024.14.0) was replacing the entire file content with `[]`, and showing the following Ruff output logs in vscode (this wasn't happening for v2024.12.0):

```
Running Ruff with: /opt/env/bin/ruff ['check', '--force-exclude', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/workspaces/myfile.py']
ERROR Exception occurred in notification: "ValueError: Position.character should be in range [0:2147483647], but was -1."
Traceback (most recent call last):
  File "/home/user/.vscode-server/extensions/charliermarsh.ruff-2024.14.0-linux-x64/bundled/libs/pygls/protocol/json_rpc.py", line 159, in _execute_notification_callback
    raise future.exception()
  File "/home/user/.vscode-server/extensions/charliermarsh.ruff-2024.14.0-linux-x64/bundled/libs/ruff_lsp/server.py", line 494, in did_change
    diagnostics = await _lint_document_impl(document, settings)
  File "/home/user/.vscode-server/extensions/charliermarsh.ruff-2024.14.0-linux-x64/bundled/libs/ruff_lsp/server.py", line 617, in _lint_document_impl
    return _parse_output(result.stdout) if result.stdout else []
  File "/home/user/.vscode-server/extensions/charliermarsh.ruff-2024.14.0-linux-x64/bundled/libs/ruff_lsp/server.py", line 703, in _parse_output
    start = Position(
  File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
    __attr_validator_character(self, __attr_character, self.character)
  File "/home/user/.vscode-server/extensions/charliermarsh.ruff-2024.14.0-linux-x64/bundled/libs/lsprotocol/validators.py", line 44, in uinteger_validator
    raise ValueError(
ValueError: Position.character should be in range [0:2147483647], but was -1.
```

The error here seemed to be because I was using an old ruff version that was incompatible with ruff-vscode > v2024.12.0:

```bash
$ ruff --version
ruff 0.0.219

$ ruff check
check:1:0: E902 No such file or directory (os error 2)
Found 1 error(s).
```

I updated both ruff and ruff-vscode to v0.7.2 & v2024.54.0 and it's all good now when saving files - maybe this information helps other users in the future :)
